Lesson 4
SergeyGildenshtern/TestGuru pull request #3
Opened 2021-12-09 09:14 UTC by SergeyGildenshtern

2021-12-09 15:52 UTC, VidgarVii requested changes

2021-12-09 15:52 UTC, VidgarVii commented on app/models/test.rb
> +    Test.joins(:category).where(categories: { title: category }).order(title: :desc).pluck(:title)
Тестируй свой код!. Этот код не будет работать. У тебя нет ассоциации category
Тут надо явно указать какие поля надо использовать при слиянии таблиц, без использования ассоциаций

2021-12-09 15:52 UTC, VidgarVii commented on app/models/user.rb
> +    Result.where(user: id).and(Result.joins(:test).where(tests: { level: level }))
Тут надо вернуть список тестов. А не результатов

2021-12-09 15:52 UTC, VidgarVii commented on db/seeds.rb
> +tests = Test.create([
лучше использовать `create!` - метод бросит исключение, если запись не создастся
сразу будет видно, если что-то пошло не так

2021-12-09 15:52 UTC, VidgarVii commented on db/seeds.rb
> +tests = Test.create([
я так понимаю сиды тоже не тестировались =(

2021-12-09 16:09 UTC, SergeyGildenshtern commented on db/seeds.rb
> +tests = Test.create([
А как я могу их затестить исли мы связи удалили?)

2021-12-10 07:47 UTC, VidgarVii commented on db/seeds.rb
> +tests = Test.create([
rails db:seed
Связи в таблицах были установлены еще на прошлом дз

2021-12-10 07:49 UTC, VidgarVii requested changes

2021-12-10 07:49 UTC, VidgarVii commented on app/models/test.rb
> +    Test.where(category: Category.where(title: category).pluck(:id)).order(title: :desc).pluck(:title)
Неплохой вариант, но через INNER JOIN будет читабельнее
Важно разобраться как работает слияние таблиц без использование ассоциаций.
Да и кейс когда нужно использовать JOIN явно указывающие поля для слияния довольно частый
Для юзеров тоже самое. Нужен JOIN

2021-12-10 07:49 UTC, VidgarVii commented on db/seeds.rb
> +  { title: 'Rails', level: 0, category: categories[1], author: users[0] }
нет такого поля в таблице author

2021-12-10 08:46 UTC, SergeyGildenshtern commented on db/seeds.rb
> +tests = Test.create([
Не работает =) Говорит нет такого атрибута category в таблице test, хотя таблицы user и category создаются

2021-12-10 13:10 UTC, VidgarVii commented on app/models/test.rb
> +  end
условия на таблицы можно (и рекомендуется, где это приемлимо) накладывать через хэши
```ruby
where(categories: { title: ... })
```
их проще изменять и легче читать

2021-12-10 13:10 UTC, VidgarVii commented on app/models/test.rb
> +  end
для удобства чтения и редактирования можно переносить зачейненные вызовы вот так:
```ruby
  joins(...)
    .where(...)
    .order(...)
    .pluck(...)
```

2021-12-15 13:01 UTC, merged